src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Models/LineasDeProduccion.cs
namespace EscuelaNet.Presentacion.Proyectos.Web.Models
{
    public class LineasDeProduccion
    {
    }
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Models/LineasIndexModel.cs
using EscuelaNet.Dominio.Proyectos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EscuelaNet.Presentacion.Proyectos.Web.Models
{
    public class LineasIndexModel
    {
        public string Titulo { get; set; }
        public List<LineaDeProduccion> LineasDeProduccion { get; set; }
    }
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Models/NuevaLineaModel.cs
using EscuelaNet.Dominio.Proyectos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EscuelaNet.Presentacion.Proyectos.Web.Models
{
    public class NuevaLineaModel
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
    }
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Controllers/DefaultController.cs
using EscuelaNet.Dominio.Proyectos;
using EscuelaNet.Presentacion.Proyectos.Web.Infraestructura;
using EscuelaNet.Presentacion.Proyectos.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EscuelaNet.Presentacion.Proyectos.Web.Controllers
{
    public class LineasController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            var lineasDeProduccion = 
                Contexto.Instancia.LineasDeProduccion;
            var model = new LineasIndexModel()
            {
                Titulo = "Primera pruba",
                LineasDeProduccion = lineasDeProduccion
            };
            return View(model);
        }

        public ActionResult New()
        {
            var model = new NuevaLineaModel();
            return View(model);

        }
        [HttpPost]
        public ActionResult New(NuevaLineaModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre))
            {
                try
                {
                    Contexto.Instancia.LineasDeProduccion.Add(new LineaDeProduccion()
                    {
                        Nombre = model.Nombre
                    });
                    TempData["success"] = "Linea de producción creada";
                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }
               
            }
            else
            {
                TempData["error"] = "Texto vacio";
                return View(model);

            }

        }

        public ActionResult Edit(int id)
        {
            var linea = Contexto.Instancia.LineasDeProduccion[id];
            var model = new NuevaLineaModel() {
                Nombre = linea.Nombre,
                Id = id
            };
            return View(model);

        }
        [HttpPost]
        public ActionResult Edit(NuevaLineaModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre))
            {
                try
                {
                    Contexto.Instancia.LineasDeProduccion[model.Id].Nombre 
                        = model.Nombre;
                    TempData["success"] = "Linea de producción editada";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }

            }
            else
            {
                TempData["error"] = "Texto vacio";
                return View(model);

            }

        }
        public ActionResult Delete(int id)
        {
            var linea = Contexto.Instancia.LineasDeProduccion[id];
            var model = new NuevaLineaModel()
            {
                Nombre = linea.Nombre,
                Id = id
            };
            return View(model);

        }
        [HttpPost]
        public ActionResult Delete(NuevaLineaModel model)
        {
           
                try
                {
                    Contexto.Instancia.LineasDeProduccion.RemoveAt(model.Id);
                    TempData["success"] = "Linea de producción borrada";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }

           

        }


    }
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EscuelaNet.Presentacion.Proyectos.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Lineas/Delete.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevaLineaModel

@{
    ViewBag.Title = "Borrar";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Borrar linea de producción</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model=>model.Id)
                    <div class="box-body">
                        <p>
                            ¿Está seguro de borrar la linea "@Model.Nombre"?
                        </p>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>

}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Lineas/Edit.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevaLineaModel

@{
    ViewBag.Title = "Editar";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Nueva linea de producción</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model=>model.Id)
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>

}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Lineas/Index.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.LineasIndexModel

@{
    ViewBag.Title = "Index";
    var x = 1;
    for (var i = 10; i > 0; i--)
    {
        x *= i;
    }
}

<div class="row">
        <div class="col-md-6">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Lineas de Producción</h3>
                <label class="text-success">@TempData["success"]</label>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-bordered">
                  <tbody>
                      <tr>
                          <th style="width: 10px">#</th>
                          <th>Título</th>
                          <th>Acciones</th>
                      </tr>
                      @foreach (var linea in Model.LineasDeProduccion)
                      {
                          <tr>
                              <td>@Model.LineasDeProduccion.IndexOf(linea)</td>
                              <td>@linea.Nombre</td>
                              <td>
                                  <a href="/Lineas/edit/@Model.LineasDeProduccion.IndexOf(linea)" title="Editar" class="btn btn-toolbar">
                                      <label class="label bg-gray"><i class="fa fa-edit"></i> Editar</label>
                                  </a>
                                  <a href="/Lineas/delete/@Model.LineasDeProduccion.IndexOf(linea)" title="borrar" class="btn btn-toolbar">
                                      <label class="label bg-gray"><i class="fa fa-remove"></i> Borrar</label>
                                  </a>
                              </td>
                          </tr>

                      }
                      <tr>
                          <td></td>
                          <td></td>
                          <td>
                              <a href="/lineas/new" title="Nuevo" class="btn btn-toolbar">
                                  <label class="label bg-gray"><i class="fa fa-plus"></i> Nuevo</label>
                              </a>
                          </td>
                      </tr>
                  </tbody></table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
              <ul class="pagination pagination-sm no-margin pull-right">
                <li><a href="#">«</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">»</a></li>
              </ul>
            </div>
          </div>
          <!-- /.box -->

          <!-- /.box -->
        </div>
        <!-- /.col -->
        <!-- /.col -->
      </div></p>

@section Scripts{
    <script>
    </script>
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Lineas/New.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevaLineaModel

@{
    ViewBag.Title = "New";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Nueva linea de producción</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>

}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @RenderSection("Header", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Lineas de Producción","Index","Lineas")</li>
                    <li><a href="/Lineas" title="Lineas de Producción">Lineas de Producción</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: true)
</body>
</html>